## library packages

if (!require("reshape2", quietly = TRUE)) install.packages("reshape2")
if (!require("ggplot2", quietly = TRUE)) install.packages("ggplot2")
if (!require("devtools", quietly = TRUE)) install.packages("devtools")
if (!require("DT", quietly = TRUE)) devtools::install_github('rstudio/DT')

if (!require(gplots, quietly = TRUE)) install.packages(gplots)
if (!require(biomaRt, quietly = TRUE)) install.packages(biomaRt)
if (!require(require(RBGL, quietly = TRUE)) install.packages(require(RBGL)
if (!require(dplyr, quietly = TRUE)) install.packages(dplyr)
if (!require(tidyr, quietly = TRUE)) install.packages(tidyr)
if (!require(RColorBrewer, quietly = TRUE)) install.packages(RColorBrewer)
if (!require(pheatmap, quietly = TRUE)) install.packages(pheatmap)
if (!require(shinyBS, quietly = TRUE)) install.packages(shinyBS)
if (!require(plotly, quietly = TRUE)) install.packages(plotly)
if (!require(markdown, quietly = TRUE)) install.packages(markdown)
if (!require(scales, quietly = TRUE)) install.packages(scales)
if (!require(heatmaply, quietly = TRUE)) install.packages(heatmaply)
if (!require(readr, quietly = TRUE)) install.packages(readr)
if (!require(colourpicker, quietly = TRUE)) install.packages(colourpicker)
if (!require(data.table, quietly = TRUE)) install.packages(data.table)
if (!require(janitor, quietly = TRUE)) install.packages(janitor)
if (!require(clusterProfiler, quietly = TRUE)) install.packages(clusterProfiler)
if (!require(fdrtool, quietly = TRUE)) install.packages(fdrtool)
if (!require(qvalue, quietly = TRUE)) install.packages(qvalue)
if (!require(RCurl, quietly = TRUE)) install.packages(RCurl)
if (!require(msigdbr, quietly = TRUE)) install.packages(msigdbr)
if (!require(enrichplot, quietly = TRUE)) install.packages(enrichplot)
if (!require(cowplot, quietly = TRUE)) install.packages(cowplot)
if (!require(ggplotify, quietly = TRUE)) install.packages(ggplotify)
if (!require(patchwork, quietly = TRUE)) install.packages(patchwork)
if (!require(esquisse, quietly = TRUE)) install.packages(esquisse)
if (!require(shinythemes, quietly = TRUE)) install.packages(shinythemes)
if (!require(gridExtra, quietly = TRUE)) install.packages(gridExtra)
if (!require(grid, quietly = TRUE)) install.packages(grid)

