## library packages


library(reshape2)
library(ggplot2)
library(gplots)
require(RBGL)
library(dplyr)
library(tidyr)
library(DT) #devtools::install_github('ramnathv/htmlwidgets'); devtools::install_github('rstudio/DT')
library(RColorBrewer)
#library(pheatmap)
library(shinyBS)
library(plotly)
library(markdown)
library(scales)
#library(heatmaply)
library(readr)
library(colourpicker)
library(data.table)
library(janitor)
library(clusterProfiler)
library(fdrtool)
library(qvalue)
#library(pubmed.mineR)
library(RCurl)
library(msigdbr)
library(enrichplot)
library(cowplot)
library(ggplotify)
library(patchwork)
#library(esquisse)
library(shinythemes)
library(gridExtra)
library(grid)

